### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by zqlq4ever** [ZS-ZhangsShun/EasyMqttAndroidClient#7]
7-18 14:03:16.062 17253-17361/com.zs.easy.mqtt.demo D/AlarmPingSender: Unregister alarmreceiver to MqttServiceNAbZ9

07-18 14:03:16.121 17253-17253/com.zs.easy.mqtt.demo I/EasyMqttService: mqtt connect failed

**Comment by ZS-ZhangsShun** [comment]
对比 demo排查过了吗  如何了现在？

**Comment by Hn1993** [comment]
我用Chrome浏览器的MQTTLens插件本地测试，报EasyMqttService: mqtt connect failed,使用的是GitHub下载的demo, serverUrl("tcp://127.0.0.1:1883")

**Comment by zqlq4ever** [comment]
> 对比 demo排查过了吗 如何了现在？

网络问题，公司内网，对服务器部署的mqtt的网做了限制，改为外网好了
